version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - backend
    

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
