version: '3.8'

services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    depends_on:
      - backend
