services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app  
      - /app/node_modules
    depends_on:
      - backend
    command: npm start 
