"""Create roles

Revision ID: 1603ae2a804d
Revises: 47e3a6de4b90
Create Date: 2025-01-02 16:23:49.254872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '1603ae2a804d'
down_revision: Union[str, None] = '47e3a6de4b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = ENUM('admin', 'user', name='user_roles', create_type=True)


def upgrade() -> None:
    # Create the enum type in the database
    role_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', role_enum, nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Drop the enum type
    role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
