"""initial migration do

Revision ID: 22ecb240e943
Revises: 1603ae2a804d
Create Date: 2025-01-16 12:08:06.266707

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import ENUM
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ecb240e943'
down_revision: Union[str, None] = '1603ae2a804d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    note_type_enum = ENUM('assignment', 'lecture_note', 'exam', name='note_type', schema='public')
    note_type_enum.create(op.get_bind())
    op.add_column('notes', sa.Column('type', note_type_enum, nullable=False))
    op.add_column('notes', sa.Column('course_id', sa.Integer(), nullable=False))
    op.drop_constraint('notes_topic_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'courses', ['course_id'], ['_id'], ondelete='CASCADE')
    op.drop_column('notes', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_topic_id_fkey', 'notes', 'topics', ['topic_id'], ['_id'], ondelete='CASCADE')
    op.drop_column('notes', 'course_id')
    op.drop_column('notes', 'type')
    # ### end Alembic commands ###
